export type OrganizationType = 'hc' | 'ra' | 'none';

export type AccessContext = {
  isAuthenticated: boolean;
  organizationType: OrganizationType;
  isAdmin: boolean;
  isSysAdmin: boolean;
  pivotEntitlements: string[];
  subscriptionCapabilities: string[];
  rolloutFlags: string[];
};

export type Capabilities = {
  canEnterShell: boolean;
  canViewDashboard: boolean;
  canViewNotifications: boolean;
  canUseInbox: boolean;
  canOpenAccountArea: boolean;
  canLogout: boolean;
  canSeeNavSection: boolean;
  canManageCareersPage: boolean;
  canManageApplicationPage: boolean;
  canManageJobListings: boolean;
  canManageHiringFlowSettings: boolean;
  canManageCustomFields: boolean;
  canManageTemplates: boolean;
  canViewJobsList: boolean;
  canCreateJob: boolean;
  canEditJob: boolean;
  canResetJobWorkflow: boolean;
  canViewJobDetail: boolean;
  canManageJobState: boolean;
  canOpenJobTask: boolean;
  canScheduleInterviewFromJob: boolean;
  canCreateOfferFromJob: boolean;
  canRejectCvFromJob: boolean;
  canUseJobRequisitionBranching: boolean;
  canManageJobAssignments: boolean;
  canViewCandidateDetail: boolean;
  canNavigateCandidateSequence: boolean;
  canOpenCandidateAction: boolean;
  canScheduleInterviewFromCandidate: boolean;
  canCreateOfferFromCandidate: boolean;
  canRejectCandidate: boolean;
  canMoveCandidateStage: boolean;
  canHireCandidate: boolean;
  canRequestCandidateReview: boolean;
  canManageCandidateDocuments: boolean;
  canViewCandidateContracts: boolean;
  canViewCandidateSurveys: boolean;
  canEditCandidateCustomFields: boolean;
  canViewInterviewFeedback: boolean;
  canCommentOnCandidate: boolean;
  canTagCandidate: boolean;
  canOpenCandidateConversation: boolean;
};
