export const routeClasses = {
  publicToken: 'Public/Token',
  page: 'Page',
  pageWithStatefulUrl: 'PageWithStatefulUrl',
  routedOverlay: 'RoutedOverlay',
  shellOverlay: 'ShellOverlay',
  taskFlow: 'TaskFlow',
} as const;

export type RouteClass = (typeof routeClasses)[keyof typeof routeClasses];

export const routeIds = {
  publicHome: 'public.home',
  confirmRegistration: 'auth.confirm-registration',
  forgotPassword: 'auth.forgot-password',
  resetPassword: 'auth.reset-password',
  register: 'auth.register',
  authCezanne: 'auth.cezanne',
  authCezanneCallback: 'auth.cezanne-callback',
  authSaml: 'auth.saml',
  inviteToken: 'auth.invite-token',
  sharedJob: 'public-external.shared-job',
  publicApplication: 'public-external.application',
  publicSurvey: 'public-external.survey',
  externalTokenizedChat: 'public-external.external-chat',
  requisitionApproval: 'public-external.requisition-approval',
  externalInterviewRequest: 'public-external.external-review.interview-request',
  externalReviewCandidate: 'public-external.external-review.review-candidate',
  externalInterviewFeedback: 'public-external.external-review.interview-feedback',
  integrationCvTokenEntry: 'integrations.token-entry.cv',
  integrationFormsTokenEntry: 'integrations.token-entry.forms',
  integrationJobTokenEntry: 'integrations.token-entry.job',
  integrationsAdminIndex: 'integrations.admin.index',
  integrationsAdminDetail: 'integrations.admin.detail',
  reportsIndex: 'reports.index',
  reportsFamily: 'reports.family',
  reportsLegacyCompat: 'reports.legacy.compat',
  orgTeamIndex: 'team.org.index',
  orgRecruiterVisibility: 'team.org.recruiter-visibility',
  orgInviteFoundation: 'team.org.invite-foundation',
  dashboard: 'dashboard.home',
  notifications: 'shell.notifications',
  inbox: 'inbox.home',
  careersPageSettings: 'settings.careers-application.careers-page',
  applicationPageSettings: 'settings.careers-application.application-page',
  jobListingsSettings: 'settings.careers-application.job-listings',
  jobListingEditor: 'settings.careers-application.job-listings-editor',
  operationalSettingsCompat: 'settings.operational.compat',
  operationalSettingsHiringFlow: 'settings.operational.hiring-flow',
  operationalSettingsCustomFields: 'settings.operational.custom-fields',
  operationalSettingsTemplates: 'settings.operational.templates',
  operationalSettingsRejectReasons: 'settings.operational.reject-reasons',
  platformHiringCompanies: 'sysadmin.master-data.hiring-companies',
  templatesIndex: 'settings.templates.index',
  templatesDetail: 'settings.templates.detail',
  templatesSmartQuestions: 'settings.templates.smart-questions',
  templatesDiversityQuestions: 'settings.templates.diversity-questions',
  templatesInterviewScoring: 'settings.templates.interview-scoring',
  jobsList: 'jobs.list',
  jobAuthoringCreate: 'jobs.authoring.create',
  jobAuthoringEdit: 'jobs.authoring.edit',
  jobDetail: 'jobs.detail',
  jobBidCreate: 'jobs.task.bid-create',
  jobBidView: 'jobs.task.bid-view',
  jobCvCreate: 'jobs.task.cv-create',
  jobCvView: 'jobs.task.cv-view',
  jobCvReject: 'jobs.task.cv-reject',
  jobSchedule: 'jobs.task.schedule',
  jobOffer: 'jobs.task.offer',
  candidateDatabase: 'candidates.database',
  candidateDatabaseCompat: 'candidates.database.compat',
  candidateDetail: 'candidates.detail',
  candidateSchedule: 'candidates.task.schedule',
  candidateOffer: 'candidates.task.offer',
  candidateReject: 'candidates.task.reject',
  userProfile: 'shell.user-profile',
  hiringCompanyProfile: 'shell.hiring-company-profile',
  recruitmentAgencyProfile: 'shell.recruitment-agency-profile',
  logout: 'shell.logout',
  accessDenied: 'system.access-denied',
} as const;

export type RouteId = (typeof routeIds)[keyof typeof routeIds];

export const publicExternalRoutePaths = [
  '/shared/$jobOrRole/$token/$source',
  '/$jobOrRole/application/$token/$source',
  '/surveys/$surveyuuid/$jobuuid/$cvuuid',
  '/chat/$token/$userId',
  '/job-requisition-approval',
  '/interview-request/$scheduleUuid/$cvToken',
  '/review-candidate/$code',
  '/interview-feedback/$code',
  '/integration/cv/$token',
  '/integration/cv/$token/$action',
  '/integration/forms/$token',
  '/integration/job/$token',
  '/integration/job/$token/$action',
] as const;

export const candidateDetailRoutePaths = [
  '/candidate/$candidateId',
  '/candidate/$candidateId/$jobId',
  '/candidate/$candidateId/$jobId/$status',
  '/candidate/$candidateId/$jobId/$status/$order',
  '/candidate/$candidateId/$jobId/$status/$order/$filters',
  '/candidate/$candidateId/$jobId/$status/$order/$filters/$interview',
] as const;

export const candidateScheduleRoutePaths = [
  '/candidate/$candidateId/cv/$cvId/schedule',
  '/candidate/$candidateId/$jobId/cv/$cvId/schedule',
  '/candidate/$candidateId/$jobId/$status/cv/$cvId/schedule',
  '/candidate/$candidateId/$jobId/$status/$order/cv/$cvId/schedule',
  '/candidate/$candidateId/$jobId/$status/$order/$filters/cv/$cvId/schedule',
  '/candidate/$candidateId/$jobId/$status/$order/$filters/$interview/cv/$cvId/schedule',
] as const;

export const candidateOfferRoutePaths = [
  '/candidate/$candidateId/cv/$cvId/offer',
  '/candidate/$candidateId/$jobId/cv/$cvId/offer',
  '/candidate/$candidateId/$jobId/$status/cv/$cvId/offer',
  '/candidate/$candidateId/$jobId/$status/$order/cv/$cvId/offer',
  '/candidate/$candidateId/$jobId/$status/$order/$filters/cv/$cvId/offer',
  '/candidate/$candidateId/$jobId/$status/$order/$filters/$interview/cv/$cvId/offer',
] as const;

export const candidateRejectRoutePaths = [
  '/candidate/$candidateId/cv-reject/$cvId',
  '/candidate/$candidateId/$jobId/cv-reject/$cvId',
  '/candidate/$candidateId/$jobId/$status/cv-reject/$cvId',
  '/candidate/$candidateId/$jobId/$status/$order/cv-reject/$cvId',
  '/candidate/$candidateId/$jobId/$status/$order/$filters/cv-reject/$cvId',
  '/candidate/$candidateId/$jobId/$status/$order/$filters/$interview/cv-reject/$cvId',
] as const;

export const registeredRoutePaths = [
  '/',
  '/confirm-registration/$token',
  '/forgot-password',
  '/reset-password/$token',
  '/register/$token',
  '/auth/cezanne/$tenantGuid',
  '/auth/cezanne/callback',
  '/auth/saml',
  '/users/invite-token',
  ...publicExternalRoutePaths,
  '/dashboard',
  '/notifications',
  '/inbox',
  '/integrations',
  '/integrations/$providerId',
  '/team',
  '/team/recruiters',
  '/users/invite',
  '/report',
  '/report/$family',
  '/hiring-company/report',
  '/hiring-company/report/$reportId',
  '/settings/careers-page',
  '/settings/hiring-flow',
  '/settings/custom-fields',
  '/templates',
  '/templates/smart-questions',
  '/templates/diversity-questions',
  '/templates/interview-scoring',
  '/templates/$templateId',
  '/reject-reasons',
  '/settings/application-page',
  '/settings/application-page/$settingsId',
  '/settings/application-page/$settingsId/$section',
  '/settings/application-page/$settingsId/$section/$subsection',
  '/settings/job-listings',
  '/settings/job-listings/edit',
  '/settings/job-listings/edit/$uuid',
  '/hiring-companies',
  '/candidates-database',
  '/candidates-old',
  '/candidates-new',
  '/jobs/$scope',
  '/jobs/manage',
  '/jobs/manage/$jobId',
  '/job/$jobId',
  '/job/$jobId/bid',
  '/job/$jobId/bid/$bidId',
  '/job/$jobId/cv',
  '/job/$jobId/cv/$candidateId',
  '/job/$jobId/cv-reject/$candidateId',
  '/job/$jobId/cv/$candidateId/schedule',
  '/job/$jobId/cv/$candidateId/offer',
  ...candidateDetailRoutePaths,
  ...candidateScheduleRoutePaths,
  ...candidateOfferRoutePaths,
  ...candidateRejectRoutePaths,
  '/user-profile',
  '/hiring-company-profile',
  '/recruitment-agency-profile',
  '/logout',
  '/access-denied',
] as const;

export type RegisteredRoutePath = (typeof registeredRoutePaths)[number];
