export const routeClasses = {
  publicToken: 'Public/Token',
  page: 'Page',
  pageWithStatefulUrl: 'PageWithStatefulUrl',
  routedOverlay: 'RoutedOverlay',
  shellOverlay: 'ShellOverlay',
  taskFlow: 'TaskFlow',
} as const;

export type RouteClass = (typeof routeClasses)[keyof typeof routeClasses];

export const routeIds = {
  publicHome: 'public.home',
  confirmRegistration: 'auth.confirm-registration',
  forgotPassword: 'auth.forgot-password',
  resetPassword: 'auth.reset-password',
  registerIndex: 'auth.register.index',
  register: 'auth.register',
  authCezanne: 'auth.cezanne',
  authCezanneCallback: 'auth.cezanne-callback',
  authSaml: 'auth.saml',
  inviteToken: 'auth.invite-token',
  sharedJob: 'public-external.shared-job',
  publicApplication: 'public-external.application',
  publicSurvey: 'public-external.survey',
  externalTokenizedChat: 'public-external.external-chat',
  requisitionApproval: 'public-external.requisition-approval',
  requisitionFormsDownload: 'public-external.requisition-forms.download',
  externalInterviewRequest: 'public-external.external-review.interview-request',
  externalReviewCandidate: 'public-external.external-review.review-candidate',
  externalInterviewFeedback: 'public-external.external-review.interview-feedback',
  integrationCvTokenEntry: 'integrations.token-entry.cv',
  integrationFormsTokenEntry: 'integrations.token-entry.forms',
  integrationJobTokenEntry: 'integrations.token-entry.job',
  integrationsAdminIndex: 'integrations.admin.index',
  integrationsAdminDetail: 'integrations.admin.detail',
  reportsIndex: 'reports.index',
  reportsFamily: 'reports.family',
  reportsLegacyCompat: 'reports.legacy.compat',
  orgTeamIndex: 'team.org.index',
  orgRecruiterVisibility: 'team.org.recruiter-visibility',
  orgInviteFoundation: 'team.org.invite-foundation',
  orgFavoritesIndex: 'favorites.org.index',
  orgFavoritesDetail: 'favorites.org.detail',
  orgFavoriteRequestCreate: 'favorites.org.request.create',
  orgFavoriteRequestDetail: 'favorites.org.request.detail',
  billingOverview: 'billing.overview',
  billingUpgrade: 'billing.upgrade',
  billingSms: 'billing.sms',
  billingCard: 'billing.card',
  marketplaceList: 'marketplace.ra.list',
  dashboard: 'dashboard.home',
  notifications: 'shell.notifications',
  inbox: 'inbox.home',
  careersPageSettings: 'settings.careers-application.careers-page',
  applicationPageSettings: 'settings.careers-application.application-page',
  jobListingsSettings: 'settings.careers-application.job-listings',
  jobListingEditor: 'settings.careers-application.job-listings-editor',
  operationalSettingsCompat: 'settings.operational.compat',
  operationalSettingsHiringFlow: 'settings.operational.hiring-flow',
  operationalSettingsCustomFields: 'settings.operational.custom-fields',
  operationalSettingsTemplates: 'settings.operational.templates',
  operationalSettingsRejectReasons: 'settings.operational.reject-reasons',
  settingsApiEndpoints: 'settings.api-endpoints',
  settingsFormsDocsControls: 'settings.forms-docs-controls',
  platformHiringCompanies: 'sysadmin.master-data.hiring-companies',
  platformHiringCompanyDetail: 'sysadmin.master-data.hiring-company.detail',
  platformHiringCompanyEdit: 'sysadmin.master-data.hiring-company.edit',
  platformHiringCompanySubscription: 'sysadmin.master-data.hiring-company.subscription',
  platformRecruitmentAgencies: 'sysadmin.master-data.recruitment-agencies',
  platformRecruitmentAgencyDetail: 'sysadmin.master-data.recruitment-agency.detail',
  platformRecruitmentAgencyEdit: 'sysadmin.master-data.recruitment-agency.edit',
  platformSubscriptions: 'sysadmin.master-data.subscriptions',
  platformSubscriptionDetail: 'sysadmin.master-data.subscription.detail',
  platformUsers: 'sysadmin.users.index',
  platformUserNew: 'sysadmin.users.new',
  platformUserEdit: 'sysadmin.users.edit',
  platformUserDetail: 'sysadmin.users.detail',
  platformFavoriteRequests: 'sysadmin.favorite-requests.index',
  platformFavoriteRequestDetail: 'sysadmin.favorite-requests.detail',
  platformSectors: 'sysadmin.taxonomy.sectors',
  platformSectorDetail: 'sysadmin.taxonomy.sector.detail',
  platformSectorSubsectors: 'sysadmin.taxonomy.sector.subsectors',
  platformSubsectorDetail: 'sysadmin.taxonomy.subsector.detail',
  templatesIndex: 'settings.templates.index',
  templatesDetail: 'settings.templates.detail',
  templatesSmartQuestions: 'settings.templates.smart-questions',
  templatesDiversityQuestions: 'settings.templates.diversity-questions',
  templatesInterviewScoring: 'settings.templates.interview-scoring',
  jobsList: 'jobs.list',
  jobAuthoringCreate: 'jobs.authoring.create',
  jobAuthoringEdit: 'jobs.authoring.edit',
  jobDetail: 'jobs.detail',
  jobBidCreate: 'jobs.task.bid-create',
  jobBidView: 'jobs.task.bid-view',
  jobCvCreate: 'jobs.task.cv-create',
  jobCvView: 'jobs.task.cv-view',
  jobCvReject: 'jobs.task.cv-reject',
  jobSchedule: 'jobs.task.schedule',
  jobOffer: 'jobs.task.offer',
  requisitionBuild: 'jobs.requisition.build',
  requisitionWorkflow: 'jobs.requisition.workflow',
  requisitionWorkflowsSettings: 'settings.hiring-flow.requisition-workflows',
  candidateDatabase: 'candidates.database',
  candidateDetail: 'candidates.detail',
  candidateSchedule: 'candidates.task.schedule',
  candidateOffer: 'candidates.task.offer',
  candidateReject: 'candidates.task.reject',
  userSettings: 'settings.user-settings',
  companySettings: 'settings.company-settings',
  agencySettings: 'settings.agency-settings',
  userProfile: 'shell.user-profile',
  hiringCompanyProfile: 'shell.hiring-company-profile',
  recruitmentAgencyProfile: 'shell.recruitment-agency-profile',
  logout: 'shell.logout',
  sessionLoss: 'shell.session-loss',
  accessDenied: 'system.access-denied',
} as const;

export type RouteId = (typeof routeIds)[keyof typeof routeIds];

export const publicExternalRoutePaths = [
  '/shared/$jobOrRole/$token/$source',
  '/$jobOrRole/application/$token/$source',
  '/surveys/$surveyuuid/$jobuuid/$cvuuid',
  '/chat/$token/$userId',
  '/job-requisition-approval',
  '/job-requisition-forms/$formId',
  '/interview-request/$scheduleUuid/$cvToken',
  '/review-candidate/$code',
  '/interview-feedback/$code',
  '/integration/cv/$token',
  '/integration/cv/$token/$action',
  '/integration/forms/$token',
  '/integration/job/$token',
  '/integration/job/$token/$action',
] as const;

export const candidateDetailRoutePaths = [
  '/candidate/$candidateId',
  '/candidate/$candidateId/$jobId',
  '/candidate/$candidateId/$jobId/$status',
  '/candidate/$candidateId/$jobId/$status/$order',
  '/candidate/$candidateId/$jobId/$status/$order/$filters',
  '/candidate/$candidateId/$jobId/$status/$order/$filters/$interview',
] as const;

export const candidateScheduleRoutePaths = [
  '/candidate/$candidateId/cv/$cvId/schedule',
  '/candidate/$candidateId/$jobId/cv/$cvId/schedule',
  '/candidate/$candidateId/$jobId/$status/cv/$cvId/schedule',
  '/candidate/$candidateId/$jobId/$status/$order/cv/$cvId/schedule',
  '/candidate/$candidateId/$jobId/$status/$order/$filters/cv/$cvId/schedule',
  '/candidate/$candidateId/$jobId/$status/$order/$filters/$interview/cv/$cvId/schedule',
] as const;

export const candidateOfferRoutePaths = [
  '/candidate/$candidateId/cv/$cvId/offer',
  '/candidate/$candidateId/$jobId/cv/$cvId/offer',
  '/candidate/$candidateId/$jobId/$status/cv/$cvId/offer',
  '/candidate/$candidateId/$jobId/$status/$order/cv/$cvId/offer',
  '/candidate/$candidateId/$jobId/$status/$order/$filters/cv/$cvId/offer',
  '/candidate/$candidateId/$jobId/$status/$order/$filters/$interview/cv/$cvId/offer',
] as const;

export const candidateRejectRoutePaths = [
  '/candidate/$candidateId/cv-reject/$cvId',
  '/candidate/$candidateId/$jobId/cv-reject/$cvId',
  '/candidate/$candidateId/$jobId/$status/cv-reject/$cvId',
  '/candidate/$candidateId/$jobId/$status/$order/cv-reject/$cvId',
  '/candidate/$candidateId/$jobId/$status/$order/$filters/cv-reject/$cvId',
  '/candidate/$candidateId/$jobId/$status/$order/$filters/$interview/cv-reject/$cvId',
] as const;

export const registeredRoutePaths = [
  '/',
  '/confirm-registration/$token',
  '/forgot-password',
  '/reset-password/$token',
  '/register',
  '/register/$token',
  '/auth/cezanne/$tenantGuid',
  '/auth/cezanne/callback',
  '/auth/saml',
  '/users/invite-token',
  ...publicExternalRoutePaths,
  '/dashboard',
  '/notifications',
  '/inbox',
  '/integrations',
  '/integrations/$providerId',
  '/team',
  '/team/recruiters',
  '/users/invite',
  '/users',
  '/users/new',
  '/users/edit/$userId',
  '/users/$userId',
  '/favorites-request',
  '/favorites-request/$requestId',
  '/favorites',
  '/favorites/request',
  '/favorites/request/$requestId',
  '/favorites/$favoriteId',
  '/billing',
  '/billing/upgrade',
  '/billing/sms',
  '/billing/card/$cardId',
  '/jobmarket/$type',
  '/report',
  '/report/$family',
  '/hiring-company/report',
  '/hiring-company/report/$reportId',
  '/settings/careers-page',
  '/settings/hiring-flow',
  '/settings/custom-fields',
  '/settings/api-endpoints',
  '/settings/forms-docs',
  '/parameters',
  '/parameters/$settingsId',
  '/parameters/$settingsId/$section',
  '/parameters/$settingsId/$section/$subsection',
  '/templates',
  '/templates/smart-questions',
  '/templates/diversity-questions',
  '/templates/interview-scoring',
  '/templates/$templateId',
  '/reject-reasons',
  '/settings/application-page',
  '/settings/application-page/$settingsId',
  '/settings/application-page/$settingsId/$section',
  '/settings/application-page/$settingsId/$section/$subsection',
  '/settings/job-listings',
  '/settings/job-listings/edit',
  '/settings/job-listings/edit/$uuid',
  '/hiring-companies',
  '/hiring-companies/$companyId',
  '/hiring-companies/edit/$companyId',
  '/hiring-company/$companyId/subscription',
  '/recruitment-agencies',
  '/recruitment-agencies/$agencyId',
  '/recruitment-agencies/edit/$agencyId',
  '/subscriptions',
  '/subscriptions/$subscriptionId',
  '/sectors',
  '/sectors/$sectorId',
  '/sectors/$sectorId/subsectors',
  '/subsectors/$subsectorId',
  '/candidates-database',
  '/jobs/$scope',
  '/jobs/manage',
  '/jobs/manage/$jobId',
  '/job/$jobId',
  '/job/$jobId/bid',
  '/job/$jobId/bid/$bidId',
  '/job/$jobId/cv',
  '/job/$jobId/cv/$candidateId',
  '/job/$jobId/cv-reject/$candidateId',
  '/job/$jobId/cv/$candidateId/schedule',
  '/job/$jobId/cv/$candidateId/offer',
  '/build-requisition',
  '/job-requisitions/$jobWorkflowUuid',
  '/job-requisitions/$jobWorkflowUuid/$jobStageUuid',
  '/requisition-workflows',
  ...candidateScheduleRoutePaths,
  ...candidateOfferRoutePaths,
  ...candidateRejectRoutePaths,
  ...candidateDetailRoutePaths,
  '/settings/user-settings',
  '/settings/company-settings',
  '/settings/agency-settings',
  '/user-profile',
  '/hiring-company-profile',
  '/recruitment-agency-profile',
  '/logout',
  '/session-lost',
  '/access-denied',
] as const;

export type RegisteredRoutePath = (typeof registeredRoutePaths)[number];
